Enable automatic syncing with upstream
snapcrafters/signal-desktop pull request #75
Opened 2022-11-16 17:48 UTC by galgalesh

To make it easier to keep this snap up to date, I propose to add this action that updates the repo automatically when a new release is detected. (this automatically runs daily)

So the new workflow is:

* Action detects a new version and commits it
* Store detects changes and rebuilds to edge
* We test and manually push to stable

This should make my job a lot easier. What do you think? The main downside I see is that I have to give myself permission to override branch protections (or create a new bot account specially for this?)

PS: In the future, I'd like the building and publishing to also happen using actions, so we can publish to `candidate` instead, and I can get a notification when it's ready for testing.

2022-11-16 17:50 UTC, galgalesh commented
Another option is to keep the logic that downloads the latest version and trigger the snap store's "rebuild" logic when I see the version in the store is different from the latest release. However, I think having the version in the repository is a better approach because it gives us more reproducibility and it allows us to rebuild the snap without getting the latest version of the app itself.

2022-11-23 20:40 UTC, zyga commented on .github/workflows/sync-release.yml
> +        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
IIRC this is now deprecated.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It should be replaced with:
```
modified=... >> $GITHUB_OUTPUT
```

2022-11-23 20:57 UTC, galgalesh commented
Fixed, but builds are now failing because of ubuntu repos being down..

2022-11-25 19:41 UTC, diddledani requested changes
We can probably use `plugin: dump`:

```yaml
  parts:
    signal-desktop:
      plugin: dump
      source: https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_$SNACPRAFT_PROJECT_VERSION_amd64.deb
      build-packages:
        - gcc
        - wget
        - jq
        - dpkg
        - git
      stage-packages:
        - libxss1
        - libnspr4
        - libnss3
        - libvips42
      override-build: |
        set -xeu
        craftctl default
        sed -i 's|Icon=signal-desktop|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/signal-desktop.png|' $CRAFT_PART_INSTALL/usr/share/applications/signal-desktop.desktop
      prime:
        - opt
        - usr/share
        - usr/lib/*/libxss*
        - usr/lib/*/*nss*
        - usr/lib/*/libvips*
        - usr/lib/*/libI*
        - usr/lib/*/libMagic*
        - usr/lib/*/libcfit*
        - usr/lib/*/libcgif*
        - usr/lib/*/libexif*
        - usr/lib/*/libfftw*
        - usr/lib/*/libgsf*
        - usr/lib/*/libheif*
        - usr/lib/*/libimage*
        - usr/lib/*/libmat*
        - usr/lib/*/libopensli*
        - usr/lib/*/libwebp*
        - usr/lib/*/libHalf*
        - usr/lib/*/libaom*
        - usr/lib/*/libdav1d*
        - usr/lib/*/libx265*
        - usr/lib/*/libhdf*
        - usr/lib/*/libsz*
        - usr/lib/*/liblqr*
        - usr/lib/*/libaec*
        - usr/lib/*/libde265*
        - usr/lib/*/libnuma*
        - -opt/Signal/chrome-sandbox
        - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
        - -opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include
```

2022-12-03 17:10 UTC, merlijn-sebrechts commented on .github/workflows/sync-release.yml
> +      - uses: actions/checkout@v2
Thanks, fixed!

2022-12-03 17:10 UTC, merlijn-sebrechts commented
Thanks, @diddledani , I greatly cleaned up the logic. The dump plugin does everything correctly for us.

2022-12-04 16:20 UTC, diddledani approved these changes
LGTM. For a followup, it looks like snapcore/action-build#42 is now fixed so we can try to revert to the `ubuntu-latest` runner once this is merged.

2022-12-05 18:41 UTC, merlijn-sebrechts commented
Thanks, I'll try it in the next refactor. I'll merge this PR, rename this branch to `candidate`, and work on the auto-publishing logic.

2022-12-05 18:41 UTC, merged